#pragma once

/**
 * @file aurora.h
 * @brief 单一包含入口（规格 §2/§24：one import / one namespace）。
 *
 * 包含全部抽象层公共模块；任何翻译单元只需 `#include "aurora/aurora.h"` 即可使用
 * Surface/Window/Painter/FontEngine/事件 等整套抽象 API。
 * **真实平台窗口 Surface**（GLFW/Win32）需另行 `#include "aurora/window/native_surfaces.h"`，
 * 并经 `create_window`（window/window.h）统一构造。无头渲染工具见 render/offscreen.h。
 *
 * 推荐别名（规格 §2）：
 * @code
 *   #include "aurora/aurora.h"
 *   using namespace aurora;   // 或只用 au:: 前缀
 *   // au::Text("Hi").font_size(14);
 * @endcode
 */
#include "aurora/animation/animator.h"
#include "aurora/animation/easing.h"
#include "aurora/animation/spring.h"
#include "aurora/animation/timeline.h"
#include "aurora/app/application.h"
#include "aurora/app/file_dialog.h"
#include "aurora/app/generate_ui.h"
#include "aurora/app/hot_reload.h"
#include "aurora/app/menu.h"
#include "aurora/app/perf_overlay.h"
#include "aurora/app/scene.h"
#include "aurora/app/scheduler.h"
#include "aurora/app/shortcuts.h"
#include "aurora/app/system_tray.h"
#include "aurora/app/validate.h"
#include "aurora/app/validate_ui.h"
#include "aurora/commands.h"
#include "aurora/core/accessibility.h"
#include "aurora/core/assert.h"
#include "aurora/core/color.h"
#include "aurora/core/debug.h"
#include "aurora/debug/debug_backend.h" // 真实后端 DEBUG 门面：capture / surface_state / 输出目录 API
#include "aurora/debug/debug_paint.h"    // 可视化调试叠层 + 控件拾取：DebugPaintFlags / widget_picker
#include "aurora/debug/debug_runtime.h"   // 运行时信息导出：widget_tree / perf_snapshot / frame_phase_timeline / why_trace / diagnostics
#include "aurora/debug/debug_trace.h"     // why_trace 热路径埋点声明（轻量）
#include "aurora/core/diagnostics.h"
#include "aurora/core/duration.h"
#include "aurora/core/event_stream.h"
#include "aurora/core/file_watcher.h"
#include "aurora/core/font.h"
#include "aurora/core/image.h"
#include "aurora/core/immutable.h"
#include "aurora/core/literals.h"
#include "aurora/core/log.h"
#include "aurora/core/platform.h"
#include "aurora/core/result.h"
#include "aurora/core/strict_mode.h"
#include "aurora/core/thread.h"
#include "aurora/core/thread_pool.h"
#include "aurora/core/time.h"
#include "aurora/core/types.h"
#include "aurora/core/version.h"
#include "aurora/environment/build_context.h"
#include "aurora/environment/environment.h"
#include "aurora/environment/media_query.h"
#include "aurora/event/dispatcher.h"
#include "aurora/event/event.h"
#include "aurora/event/focus.h"
#include "aurora/event/keycode.h"
#include "aurora/i18n/localized_string.h"
#include "aurora/i18n/string_table.h"
#include "aurora/layout/flex.h"
#include "aurora/layout/flex_layouter.h"
#include "aurora/layout/layout_box.h"
#include "aurora/layout/layout_engine.h"
#include "aurora/modifier/modifier.h"
#include "aurora/navigation/hero.h"
#include "aurora/navigation/navigator.h"
#include "aurora/navigation/route.h"
#include "aurora/navigation/router.h"
#include "aurora/perf/counters.h"
#include "aurora/perf/perf_log.h"
#include "aurora/perf/perf_session.h"
#include "aurora/perf/profiler.h"
#include "aurora/perf/scroll_bench.h"
#include "aurora/perf/stopwatch.h"
#include "aurora/perf/trace_writer.h"
#include "aurora/render/dirty_region.h"
#include "aurora/render/font_engine.h"
#include "aurora/render/image_cache.h"
#include "aurora/render/offscreen.h"
#include "aurora/render/painter.h"
#include "aurora/render/png.h"
#include "aurora/render/snapshot_diff.h"
#include "aurora/state/async.h"
#include "aurora/state/binding.h"
#include "aurora/state/computed.h"
#include "aurora/state/coroutine.h"
#include "aurora/state/effect.h"
#include "aurora/state/reactive.h"
#include "aurora/state/signal_view.h"
#include "aurora/state/state.h"
#include "aurora/state/state_graph.h"
#include "aurora/state/store.h"
#include "aurora/state/subscription.h"
#include "aurora/state/undo_stack.h"
#include "aurora/todo.h"

// 轻量持久化配置（JSON 文件后端，对标 SharedPreferences / UserDefaults）
#include "aurora/media/image_sequence_source.h"
#include "aurora/media/video_controls.h"
#include "aurora/media/video_player.h"
#include "aurora/media/video_source.h"
#include "aurora/preferences/preferences.h"
// 数据存储抽象层（可切换后端：Memory / Filesystem / 未来 SQLite；默认 Filesystem）
#include "aurora/storage/storage.h"
#include "aurora/theming/style_props.h"
#include "aurora/theming/theme.h"
#include "aurora/theming/theme_query.h"
#include "aurora/theming/theme_scope.h"
#include "aurora/ui/factories.h"
#include "aurora/widget/button.h"
#include "aurora/widget/canvas.h"
#include "aurora/widget/checkbox.h"
#include "aurora/widget/chip.h"
#include "aurora/widget/containers.h"
#include "aurora/widget/data_widgets.h"
#include "aurora/widget/divider.h"
#include "aurora/widget/drawer.h"
#include "aurora/widget/dropdown.h"
#include "aurora/widget/expansion_panel.h"
#include "aurora/widget/form.h"
#include "aurora/widget/grid.h"
#include "aurora/widget/grid_view.h"
#include "aurora/widget/image_widget.h"
#include "aurora/widget/inspect.h"
#include "aurora/widget/inspector_panel.h"
#include "aurora/widget/layout_builder.h"
#include "aurora/widget/layout_query.h"
#include "aurora/widget/lazy_list.h"
#include "aurora/widget/lifecycle.h"
#include "aurora/widget/menu_bar.h"
#include "aurora/widget/title_bar.h"
#include "aurora/widget/pickers.h"
#include "aurora/widget/placeholder.h"
#include "aurora/widget/popup.h"
#include "aurora/widget/progress.h"
#include "aurora/widget/provider.h"
#include "aurora/widget/radio_spin.h"
#include "aurora/widget/recipes.h"
#include "aurora/widget/repeater.h"
#include "aurora/widget/rich_text.h"
#include "aurora/widget/rich_text_edit.h"
#include "aurora/widget/scroll.h"
#include "aurora/widget/segmented_control.h"
#include "aurora/widget/serialization.h"
#include "aurora/widget/show.h"
#include "aurora/widget/skeleton.h"
#include "aurora/widget/slider.h"
#include "aurora/widget/spacer.h"
#include "aurora/widget/splitter.h"
#include "aurora/widget/stack.h"
#include "aurora/widget/stepper.h"
#include "aurora/widget/switch.h"
#include "aurora/widget/tab_bar.h"
#include "aurora/widget/text.h"
#include "aurora/widget/text_input.h"
#include "aurora/widget/text_span.h"
#include "aurora/widget/timer.h"
#include "aurora/widget/toast.h"
#include "aurora/widget/toolbar.h"
#include "aurora/widget/widget.h"
#include "aurora/window/frame_pacing.h" // compute_wait_timeout：事件驱动帧循环调度决策
#include "aurora/window/platform.h"     // au::platform()：平台与运行环境显式查询
#include "aurora/window/surface.h"
#include "aurora/window/window.h"

namespace au = aurora; ///< 推荐短别名（规格 §2）。`au::colors::Red` 经别名直接可用。
