// ============================================================================
// 本文件由 tools/gen_error_codes.cpp 自动生成，请勿手改。
// 修改请编辑 codespec/errors.toml 后重新运行生成器。
// ============================================================================
#pragma once
#include <array>
#include <cstdint>
#include <string>
#include <string_view>
#include <unordered_map>

namespace aurora {

/// @brief 错误参数的键值表（message 模板 {key} 由它渲染）
using ErrorParams = std::unordered_map<std::string, std::string>;

enum class ErrorCategory : std::uint8_t {
    General = 0,
    Layout = 1,
    Widget = 2,
    Render = 3,
    Io = 4,
    Validation = 5,
    Navigation = 6,
    Platform = 7,
    Runtime = 8,
    Generation = 9,
    Diagnostic = 10,
};

enum class ErrorSeverity : std::uint8_t {
    Info = 0,
    Warning = 1,
    Error = 2,
    Fatal = 3,
};

enum class ErrorCode : std::uint16_t {
    GeneralUnknown = 0,
    GeneralInvalidArgument = 1,
    GeneralNotSupported = 2,
    LayoutNullChild = 3,
    LayoutDepthExceeded = 4,
    LayoutInvalidConstraints = 5,
    LayoutSizeOutOfConstraints = 6,
    WidgetUnknownType = 7,
    WidgetInvalidProp = 8,
    WidgetPropConstraintViolated = 9,
    WidgetMissingRequiredProp = 10,
    RenderFontLoadFailed = 11,
    RenderImageLoadFailed = 12,
    RenderInvalidColor = 13,
    IOFileNotFound = 14,
    IOParseFailed = 15,
    IOImageDecodeFailed = 16,
    IOImageInvalidDimensions = 17,
    ValidationFailed = 18,
    ValidationSchemaMismatch = 19,
    ValidationTreeTooDeep = 20,
    ValidationUnknownWidget = 21,
    ValidationNullChild = 22,
    NavDepthExceeded = 23,
    NavRouteNotFound = 24,
    PlatformUnavailable = 25,
    PlatformPermissionDenied = 26,
    PlatformComInitFailed = 27,
    PlatformDialogCreateFailed = 28,
    RuntimeCoroutineException = 29,
    RuntimeAsyncException = 30,
    RuntimeAsyncTimeout = 31,
    GenerateUiEmpty = 32,
    RendererUnavailable = 33,
    PrefsNotPersistent = 34,
    PrefsOpenFailed = 35,
    PrefsParseFailed = 36,
    PrefsWriteFailed = 37,
    WidgetDepthExceeded = 38,
    RenderDegraded = 39,
    FontMissing = 40,
    SurfaceLost = 41,
    NotRestorable = 42,
    JsonParseError = 43,
    StorageBackendUnavailable = 44,
    StorageRecordNotFound = 45,
    StorageRecordCorrupt = 46,
    StorageTypeMismatch = 47,
    StorageEncodingMismatch = 48,
    StorageIoError = 49,
};

struct ErrorMeta {
    ErrorCode code;
    std::string_view ident;         // C++ 标识符，如 "NavDepthExceeded"（调试用）
    std::string_view slug;          // 冻结对外码，如 "nav-depth-exceeded"
    ErrorCategory category;
    ErrorSeverity severity;
    bool auto_fixable;
    std::string_view fix_category;
    bool retryable;
    std::string_view message_tpl;   // 含 {placeholder}
    std::string_view hint;
};

inline constexpr std::array<ErrorMeta, 50> AURORA_ERROR_TABLE = {{
    { .code = ErrorCode::GeneralUnknown,
      .ident = "GeneralUnknown",
      .slug = "general-unknown",
      .category = ErrorCategory::General,
      .severity = ErrorSeverity::Error,
      .auto_fixable = false,
      .fix_category = "unknown",
      .retryable = false,
      .message_tpl = "An unknown error occurred",
      .hint = "Check the log context or enable the diagnostic collector", },
    { .code = ErrorCode::GeneralInvalidArgument,
      .ident = "GeneralInvalidArgument",
      .slug = "general-invalid-argument",
      .category = ErrorCategory::General,
      .severity = ErrorSeverity::Error,
      .auto_fixable = false,
      .fix_category = "invalid_value",
      .retryable = false,
      .message_tpl = "Invalid argument supplied",
      .hint = "Check the parameter type and value range", },
    { .code = ErrorCode::GeneralNotSupported,
      .ident = "GeneralNotSupported",
      .slug = "general-not-supported",
      .category = ErrorCategory::General,
      .severity = ErrorSeverity::Error,
      .auto_fixable = false,
      .fix_category = "unknown",
      .retryable = false,
      .message_tpl = "Operation not supported",
      .hint = "Confirm whether the feature is available or use an alternative", },
    { .code = ErrorCode::LayoutNullChild,
      .ident = "LayoutNullChild",
      .slug = "layout-null-child",
      .category = ErrorCategory::Layout,
      .severity = ErrorSeverity::Warning,
      .auto_fixable = true,
      .fix_category = "missing_child",
      .retryable = false,
      .message_tpl = "Layout child widget is null",
      .hint = "Remove the empty child node or provide a valid widget", },
    { .code = ErrorCode::LayoutDepthExceeded,
      .ident = "LayoutDepthExceeded",
      .slug = "layout-depth-exceeded",
      .category = ErrorCategory::Layout,
      .severity = ErrorSeverity::Warning,
      .auto_fixable = true,
      .fix_category = "layout_conflict",
      .retryable = false,
      .message_tpl = "Layout tree depth exceeded the limit (default {max})",
      .hint = "Check for infinitely recursive Repeater/Provider", },
    { .code = ErrorCode::LayoutInvalidConstraints,
      .ident = "LayoutInvalidConstraints",
      .slug = "layout-invalid-constraints",
      .category = ErrorCategory::Layout,
      .severity = ErrorSeverity::Warning,
      .auto_fixable = true,
      .fix_category = "invalid_value",
      .retryable = false,
      .message_tpl = "Invalid constraints (e.g. min > max)",
      .hint = "Check the constraints settings", },
    { .code = ErrorCode::LayoutSizeOutOfConstraints,
      .ident = "LayoutSizeOutOfConstraints",
      .slug = "layout-size-out-of-constraints",
      .category = ErrorCategory::Layout,
      .severity = ErrorSeverity::Warning,
      .auto_fixable = true,
      .fix_category = "invalid_value",
      .retryable = false,
      .message_tpl = "Computed size out of constraints range",
      .hint = "Adjust the min/max constraints or content size", },
    { .code = ErrorCode::WidgetUnknownType,
      .ident = "WidgetUnknownType",
      .slug = "widget-unknown-type",
      .category = ErrorCategory::Widget,
      .severity = ErrorSeverity::Warning,
      .auto_fixable = true,
      .fix_category = "unknown_widget",
      .retryable = false,
      .message_tpl = "Unregistered widget type '{type}' encountered during deserialization",
      .hint = "Register it first via WidgetRegistry::register_factory", },
    { .code = ErrorCode::WidgetInvalidProp,
      .ident = "WidgetInvalidProp",
      .slug = "widget-invalid-prop",
      .category = ErrorCategory::Widget,
      .severity = ErrorSeverity::Warning,
      .auto_fixable = true,
      .fix_category = "invalid_value",
      .retryable = false,
      .message_tpl = "Invalid property value: '{prop}'",
      .hint = "Check the property type and value range", },
    { .code = ErrorCode::WidgetPropConstraintViolated,
      .ident = "WidgetPropConstraintViolated",
      .slug = "widget-prop-constraint-violated",
      .category = ErrorCategory::Widget,
      .severity = ErrorSeverity::Warning,
      .auto_fixable = true,
      .fix_category = "invalid_value",
      .retryable = false,
      .message_tpl = "Property constraint violated (mutually exclusive properties set together)",
      .hint = "Check the validity of the property combination", },
    { .code = ErrorCode::WidgetMissingRequiredProp,
      .ident = "WidgetMissingRequiredProp",
      .slug = "widget-missing-required-prop",
      .category = ErrorCategory::Widget,
      .severity = ErrorSeverity::Warning,
      .auto_fixable = true,
      .fix_category = "missing_prop",
      .retryable = false,
      .message_tpl = "Missing required property '{prop}'",
      .hint = "Add the missing required property", },
    { .code = ErrorCode::RenderFontLoadFailed,
      .ident = "RenderFontLoadFailed",
      .slug = "render-font-load-failed",
      .category = ErrorCategory::Render,
      .severity = ErrorSeverity::Error,
      .auto_fixable = false,
      .fix_category = "resource_error",
      .retryable = false,
      .message_tpl = "Font load failed: '{path}'",
      .hint = "Check the font path and format", },
    { .code = ErrorCode::RenderImageLoadFailed,
      .ident = "RenderImageLoadFailed",
      .slug = "render-image-load-failed",
      .category = ErrorCategory::Render,
      .severity = ErrorSeverity::Error,
      .auto_fixable = false,
      .fix_category = "resource_error",
      .retryable = false,
      .message_tpl = "Image load failed: '{path}'",
      .hint = "Check the image path, format and decoder", },
    { .code = ErrorCode::RenderInvalidColor,
      .ident = "RenderInvalidColor",
      .slug = "render-invalid-color",
      .category = ErrorCategory::Render,
      .severity = ErrorSeverity::Error,
      .auto_fixable = false,
      .fix_category = "invalid_value",
      .retryable = false,
      .message_tpl = "Invalid color value (e.g. component out of 0-255)",
      .hint = "Check the color component values", },
    { .code = ErrorCode::IOFileNotFound,
      .ident = "IOFileNotFound",
      .slug = "io-file-not-found",
      .category = ErrorCategory::Io,
      .severity = ErrorSeverity::Error,
      .auto_fixable = false,
      .fix_category = "resource_error",
      .retryable = false,
      .message_tpl = "File does not exist or cannot be opened: '{path}'",
      .hint = "Check the file path and permissions", },
    { .code = ErrorCode::IOParseFailed,
      .ident = "IOParseFailed",
      .slug = "io-parse-failed",
      .category = ErrorCategory::Io,
      .severity = ErrorSeverity::Error,
      .auto_fixable = false,
      .fix_category = "type_error",
      .retryable = false,
      .message_tpl = "File parsing failed: '{detail}'",
      .hint = "Check the file content format", },
    { .code = ErrorCode::IOImageDecodeFailed,
      .ident = "IOImageDecodeFailed",
      .slug = "io-image-decode-failed",
      .category = ErrorCategory::Io,
      .severity = ErrorSeverity::Error,
      .auto_fixable = false,
      .fix_category = "resource_error",
      .retryable = false,
      .message_tpl = "Image decode failed",
      .hint = "Check image file validity or use a supported format", },
    { .code = ErrorCode::IOImageInvalidDimensions,
      .ident = "IOImageInvalidDimensions",
      .slug = "io-image-invalid-dimensions",
      .category = ErrorCategory::Io,
      .severity = ErrorSeverity::Error,
      .auto_fixable = false,
      .fix_category = "invalid_value",
      .retryable = false,
      .message_tpl = "Invalid image dimensions (width/height is 0 or exceeds the limit)",
      .hint = "Check image dimensions or use a valid-size resource", },
    { .code = ErrorCode::ValidationFailed,
      .ident = "ValidationFailed",
      .slug = "validation-failed",
      .category = ErrorCategory::Validation,
      .severity = ErrorSeverity::Warning,
      .auto_fixable = true,
      .fix_category = "type_error",
      .retryable = false,
      .message_tpl = "Validation failed: '{detail}'",
      .hint = "Check input data validity", },
    { .code = ErrorCode::ValidationSchemaMismatch,
      .ident = "ValidationSchemaMismatch",
      .slug = "validation-schema-mismatch",
      .category = ErrorCategory::Validation,
      .severity = ErrorSeverity::Warning,
      .auto_fixable = true,
      .fix_category = "type_error",
      .retryable = false,
      .message_tpl = "Schema mismatch",
      .hint = "Check data structure against the Schema definition", },
    { .code = ErrorCode::ValidationTreeTooDeep,
      .ident = "ValidationTreeTooDeep",
      .slug = "validation-tree-too-deep",
      .category = ErrorCategory::Validation,
      .severity = ErrorSeverity::Warning,
      .auto_fixable = true,
      .fix_category = "layout_conflict",
      .retryable = false,
      .message_tpl = "UI tree depth exceeded the limit (default {max})",
      .hint = "Reduce nesting levels or split components", },
    { .code = ErrorCode::ValidationUnknownWidget,
      .ident = "ValidationUnknownWidget",
      .slug = "validation-unknown-widget",
      .category = ErrorCategory::Validation,
      .severity = ErrorSeverity::Warning,
      .auto_fixable = true,
      .fix_category = "unknown_widget",
      .retryable = false,
      .message_tpl = "Unknown/unsupported widget type '{type}'",
      .hint = "Use a known widget type or register a custom type", },
    { .code = ErrorCode::ValidationNullChild,
      .ident = "ValidationNullChild",
      .slug = "validation-null-child",
      .category = ErrorCategory::Validation,
      .severity = ErrorSeverity::Warning,
      .auto_fixable = true,
      .fix_category = "missing_child",
      .retryable = false,
      .message_tpl = "Child node is null",
      .hint = "Provide a valid child node or remove the item", },
    { .code = ErrorCode::NavDepthExceeded,
      .ident = "NavDepthExceeded",
      .slug = "nav-depth-exceeded",
      .category = ErrorCategory::Navigation,
      .severity = ErrorSeverity::Error,
      .auto_fixable = false,
      .fix_category = "layout_conflict",
      .retryable = false,
      .message_tpl = "Navigation stack depth exceeded the limit (default {max})",
      .hint = "Check the Navigator push loop logic or call set_max_depth()", },
    { .code = ErrorCode::NavRouteNotFound,
      .ident = "NavRouteNotFound",
      .slug = "nav-route-not-found",
      .category = ErrorCategory::Navigation,
      .severity = ErrorSeverity::Error,
      .auto_fixable = false,
      .fix_category = "missing_prop",
      .retryable = false,
      .message_tpl = "Route not registered: '{route}'",
      .hint = "Register the corresponding route or use the default route", },
    { .code = ErrorCode::PlatformUnavailable,
      .ident = "PlatformUnavailable",
      .slug = "platform-unavailable",
      .category = ErrorCategory::Platform,
      .severity = ErrorSeverity::Error,
      .auto_fixable = false,
      .fix_category = "resource_error",
      .retryable = false,
      .message_tpl = "Platform feature unavailable: '{detail}'",
      .hint = "Check the runtime environment or enable the corresponding backend", },
    { .code = ErrorCode::PlatformPermissionDenied,
      .ident = "PlatformPermissionDenied",
      .slug = "platform-permission-denied",
      .category = ErrorCategory::Platform,
      .severity = ErrorSeverity::Error,
      .auto_fixable = false,
      .fix_category = "resource_error",
      .retryable = false,
      .message_tpl = "Insufficient permissions: '{detail}'",
      .hint = "Check file/network permission settings", },
    { .code = ErrorCode::PlatformComInitFailed,
      .ident = "PlatformComInitFailed",
      .slug = "platform-com-init-failed",
      .category = ErrorCategory::Platform,
      .severity = ErrorSeverity::Error,
      .auto_fixable = false,
      .fix_category = "resource_error",
      .retryable = false,
      .message_tpl = "COM initialization failed",
      .hint = "Initialize COM outside the GUI thread or check the runtime environment", },
    { .code = ErrorCode::PlatformDialogCreateFailed,
      .ident = "PlatformDialogCreateFailed",
      .slug = "platform-dialog-create-failed",
      .category = ErrorCategory::Platform,
      .severity = ErrorSeverity::Error,
      .auto_fixable = false,
      .fix_category = "resource_error",
      .retryable = false,
      .message_tpl = "Platform dialog creation failed",
      .hint = "Check the parent window handle or runtime environment", },
    { .code = ErrorCode::RuntimeCoroutineException,
      .ident = "RuntimeCoroutineException",
      .slug = "runtime-coroutine-exception",
      .category = ErrorCategory::Runtime,
      .severity = ErrorSeverity::Error,
      .auto_fixable = false,
      .fix_category = "exception",
      .retryable = true,
      .message_tpl = "Exception thrown during coroutine execution: '{detail}'",
      .hint = "Check the coroutine body for exception catching or fix the logic", },
    { .code = ErrorCode::RuntimeAsyncException,
      .ident = "RuntimeAsyncException",
      .slug = "runtime-async-exception",
      .category = ErrorCategory::Runtime,
      .severity = ErrorSeverity::Error,
      .auto_fixable = false,
      .fix_category = "exception",
      .retryable = true,
      .message_tpl = "Exception thrown during async task execution: '{detail}'",
      .hint = "Check the async callback for exception catching or fix the logic", },
    { .code = ErrorCode::RuntimeAsyncTimeout,
      .ident = "RuntimeAsyncTimeout",
      .slug = "async-timeout",
      .category = ErrorCategory::Runtime,
      .severity = ErrorSeverity::Error,
      .auto_fixable = false,
      .fix_category = "timeout",
      .retryable = true,
      .message_tpl = "Async task timed out (not completed within {ms}ms)",
      .hint = "Increase the timeout threshold or optimize async task duration", },
    { .code = ErrorCode::GenerateUiEmpty,
      .ident = "GenerateUiEmpty",
      .slug = "generation-ui-empty",
      .category = ErrorCategory::Generation,
      .severity = ErrorSeverity::Error,
      .auto_fixable = false,
      .fix_category = "empty",
      .retryable = false,
      .message_tpl = "NL-to-UI generation result is empty (no valid widget)",
      .hint = "Provide a more specific natural language description or constraints", },
    { .code = ErrorCode::RendererUnavailable,
      .ident = "RendererUnavailable",
      .slug = "renderer-unavailable",
      .category = ErrorCategory::Platform,
      .severity = ErrorSeverity::Error,
      .auto_fixable = false,
      .fix_category = "resource_error",
      .retryable = false,
      .message_tpl = "Requested render backend is unavailable",
      .hint = "Check the backend compile switch (AURORA_BACKEND_D3D11) or fall back to software rendering (RendererPreference::Auto/Software)", },
    { .code = ErrorCode::PrefsNotPersistent,
      .ident = "PrefsNotPersistent",
      .slug = "prefs-not-persistent",
      .category = ErrorCategory::Platform,
      .severity = ErrorSeverity::Error,
      .auto_fixable = false,
      .fix_category = "resource_error",
      .retryable = false,
      .message_tpl = "Preferences is in memory-only mode and cannot be persisted",
      .hint = "Bind a config file path (Preferences(file)) to gain persistence", },
    { .code = ErrorCode::PrefsOpenFailed,
      .ident = "PrefsOpenFailed",
      .slug = "prefs-open-failed",
      .category = ErrorCategory::Platform,
      .severity = ErrorSeverity::Error,
      .auto_fixable = false,
      .fix_category = "resource_error",
      .retryable = false,
      .message_tpl = "Failed to open config file: '{path}'",
      .hint = "Check the file path and read permissions", },
    { .code = ErrorCode::PrefsParseFailed,
      .ident = "PrefsParseFailed",
      .slug = "prefs-parse-failed",
      .category = ErrorCategory::Platform,
      .severity = ErrorSeverity::Error,
      .auto_fixable = false,
      .fix_category = "type_error",
      .retryable = false,
      .message_tpl = "Config file JSON parse failed: '{detail}'",
      .hint = "Check JSON syntax (quotes/commas/brackets) and field types", },
    { .code = ErrorCode::PrefsWriteFailed,
      .ident = "PrefsWriteFailed",
      .slug = "prefs-write-failed",
      .category = ErrorCategory::Platform,
      .severity = ErrorSeverity::Error,
      .auto_fixable = false,
      .fix_category = "resource_error",
      .retryable = false,
      .message_tpl = "Config file write failed: '{detail}'",
      .hint = "Check disk space, whether the directory exists, and target file permissions", },
    { .code = ErrorCode::WidgetDepthExceeded,
      .ident = "WidgetDepthExceeded",
      .slug = "widget-depth-exceeded",
      .category = ErrorCategory::Widget,
      .severity = ErrorSeverity::Warning,
      .auto_fixable = true,
      .fix_category = "layout_conflict",
      .retryable = false,
      .message_tpl = "Widget tree depth exceeded the limit (default 64)",
      .hint = "Usually caused by infinitely recursive Repeater / self-referencing Provider; check rebuild conditions or set_max_depth()", },
    { .code = ErrorCode::RenderDegraded,
      .ident = "RenderDegraded",
      .slug = "render-degraded",
      .category = ErrorCategory::Render,
      .severity = ErrorSeverity::Warning,
      .auto_fixable = false,
      .fix_category = "invalid_value",
      .retryable = false,
      .message_tpl = "Rendering degraded due to missing resources (e.g. font/image fallback)",
      .hint = "Non-fatal degradation, UI remains usable; check the missing resource path or provide alternatives", },
    { .code = ErrorCode::FontMissing,
      .ident = "FontMissing",
      .slug = "font-missing",
      .category = ErrorCategory::Render,
      .severity = ErrorSeverity::Warning,
      .auto_fixable = false,
      .fix_category = "resource_error",
      .retryable = false,
      .message_tpl = "Requested font unavailable, fell back to built-in Bitmap font",
      .hint = "On non-Windows platforms the GDI font fallback chain may differ; ensure the font is registered or use the built-in font", },
    { .code = ErrorCode::SurfaceLost,
      .ident = "SurfaceLost",
      .slug = "surface-lost",
      .category = ErrorCategory::Platform,
      .severity = ErrorSeverity::Warning,
      .auto_fixable = false,
      .fix_category = "resource_error",
      .retryable = false,
      .message_tpl = "Surface lost (e.g. window destroyed/device reset)",
      .hint = "Need to rebuild the Surface to continue rendering; in most cases the framework auto-recovers on next present", },
    { .code = ErrorCode::NotRestorable,
      .ident = "NotRestorable",
      .slug = "not-restorable",
      .category = ErrorCategory::Widget,
      .severity = ErrorSeverity::Warning,
      .auto_fixable = false,
      .fix_category = "unknown",
      .retryable = false,
      .message_tpl = "Widget not restorable (skipped during serialization/deserialization)",
      .hint = "Widgets relying on runtime callbacks such as Repeater / Canvas cannot be restored from JSON; use a named factory or State injection", },
    { .code = ErrorCode::JsonParseError,
      .ident = "JsonParseError",
      .slug = "json-parse-error",
      .category = ErrorCategory::Io,
      .severity = ErrorSeverity::Error,
      .auto_fixable = false,
      .fix_category = "type_error",
      .retryable = false,
      .message_tpl = "JSON parse failed",
      .hint = "Check JSON syntax (quotes/commas/brackets) and whether field types match the Schema", },
    { .code = ErrorCode::StorageBackendUnavailable,
      .ident = "StorageBackendUnavailable",
      .slug = "storage-backend-unavailable",
      .category = ErrorCategory::Io,
      .severity = ErrorSeverity::Error,
      .auto_fixable = false,
      .fix_category = "resource_error",
      .retryable = false,
      .message_tpl = "Storage backend unavailable (directory not writable or media open failed)",
      .hint = "Check storage path permissions; when a cross-process lock is held, wait or close the occupying process", },
    { .code = ErrorCode::StorageRecordNotFound,
      .ident = "StorageRecordNotFound",
      .slug = "storage-record-not-found",
      .category = ErrorCategory::Io,
      .severity = ErrorSeverity::Error,
      .auto_fixable = false,
      .fix_category = "missing_child",
      .retryable = false,
      .message_tpl = "Storage record does not exist",
      .hint = "Confirm the id spelling; or put first then get", },
    { .code = ErrorCode::StorageRecordCorrupt,
      .ident = "StorageRecordCorrupt",
      .slug = "storage-record-corrupt",
      .category = ErrorCategory::Validation,
      .severity = ErrorSeverity::Error,
      .auto_fixable = false,
      .fix_category = "type_error",
      .retryable = false,
      .message_tpl = "Storage record corrupt (JSON parse failed or illegal structure)",
      .hint = "Delete the corrupt file or restore from backup; use clear to rebuild if necessary", },
    { .code = ErrorCode::StorageTypeMismatch,
      .ident = "StorageTypeMismatch",
      .slug = "storage-type-mismatch",
      .category = ErrorCategory::Validation,
      .severity = ErrorSeverity::Error,
      .auto_fixable = false,
      .fix_category = "type_error",
      .retryable = false,
      .message_tpl = "Typed read type mismatch",
      .hint = "Ensure put/get use the same type T; or use get_value to read the raw payload", },
    { .code = ErrorCode::StorageEncodingMismatch,
      .ident = "StorageEncodingMismatch",
      .slug = "storage-encoding-mismatch",
      .category = ErrorCategory::Validation,
      .severity = ErrorSeverity::Error,
      .auto_fixable = false,
      .fix_category = "type_error",
      .retryable = false,
      .message_tpl = "Serialized wire format mismatch",
      .hint = "Record stored as binary but type T only supports JSON (or vice versa); use get_value or fix T's serialization concept", },
    { .code = ErrorCode::StorageIoError,
      .ident = "StorageIoError",
      .slug = "storage-io-error",
      .category = ErrorCategory::Io,
      .severity = ErrorSeverity::Error,
      .auto_fixable = false,
      .fix_category = "resource_error",
      .retryable = false,
      .message_tpl = "Storage underlying I/O failed",
      .hint = "Check disk space/permissions; rename failure may be a cross-volume move, use a same-volume path", },
  },
};

constexpr auto error_count() -> std::size_t { return std::size(AURORA_ERROR_TABLE); }

constexpr auto slug(ErrorCode c) -> std::string_view {
    return AURORA_ERROR_TABLE.at(static_cast<std::size_t>(c)).slug;
}
constexpr auto category(ErrorCode c) -> ErrorCategory {
    return AURORA_ERROR_TABLE.at(static_cast<std::size_t>(c)).category;
}
constexpr auto severity(ErrorCode c) -> ErrorSeverity {
    return AURORA_ERROR_TABLE.at(static_cast<std::size_t>(c)).severity;
}
constexpr auto is_auto_fixable(ErrorCode c) -> bool {
    return AURORA_ERROR_TABLE.at(static_cast<std::size_t>(c)).auto_fixable;
}
constexpr auto fix_category_of(ErrorCode c) -> std::string_view {
    return AURORA_ERROR_TABLE.at(static_cast<std::size_t>(c)).fix_category;
}
constexpr auto retryable(ErrorCode c) -> bool {
    return AURORA_ERROR_TABLE.at(static_cast<std::size_t>(c)).retryable;
}
constexpr auto hint_of(ErrorCode c) -> std::string_view {
    return AURORA_ERROR_TABLE.at(static_cast<std::size_t>(c)).hint;
}
// 调试用：返回 C++ 标识符（可随改名变），非对外契约
constexpr auto to_string(ErrorCode c) -> std::string_view {
    return AURORA_ERROR_TABLE.at(static_cast<std::size_t>(c)).ident;
}

constexpr auto to_string(ErrorCategory c) -> std::string_view {
    switch (c) {
        case ErrorCategory::General: return "general";
        case ErrorCategory::Layout: return "layout";
        case ErrorCategory::Widget: return "widget";
        case ErrorCategory::Render: return "render";
        case ErrorCategory::Io: return "io";
        case ErrorCategory::Validation: return "validation";
        case ErrorCategory::Navigation: return "navigation";
        case ErrorCategory::Platform: return "platform";
        case ErrorCategory::Runtime: return "runtime";
        case ErrorCategory::Generation: return "generation";
        case ErrorCategory::Diagnostic: return "diagnostic";
    }
    return "unknown";
}

constexpr auto to_string(ErrorSeverity s) -> std::string_view {
    switch (s) {
        case ErrorSeverity::Info: return "info";
        case ErrorSeverity::Warning: return "warning";
        case ErrorSeverity::Error: return "error";
        case ErrorSeverity::Fatal: return "fatal";
    }
    return "error";
}

inline auto format_message(std::string_view tpl, const ErrorParams& params) -> std::string {
    std::string out;
    out.reserve(tpl.size());
    for (std::size_t i = 0; i < tpl.size(); ++i) {
        if (tpl[i] == '{') {
            std::size_t j = tpl.find('}', i);
            if (j != std::string_view::npos) {
                std::string_view key = tpl.substr(i + 1, j - i - 1);
                auto it = params.find(std::string(key));
                if (it != params.end()) {
                    out += it->second;
                    i = j;
                    continue;
                }
            }
        }
        out += tpl[i];
    }
    return out;
}

} // namespace aurora
