#!/usr/bin/env python3
# ============================================================================
# check_api_budget.py - public-API size/token budget gate (requirement #24)
# ----------------------------------------------------------------------------
# Spec: codespec/SPECIFICATIONS.md §4.3 (requirement #24 "Token 效率 + 编译速度约束")
#
# Rationale: #24 demands the public API surface stay token-efficient so AI
# iteration loops (and C++ compiles) stay fast. The frozen API SSOT is
# aurora_api.json (regenerated by gen_api_tools); its serialized size is a
# stable, machine-independent proxy for the token cost of the public surface
# an AI agent must hold in context. English code/JSON tokenizes at roughly
# 4 characters per token on common BPE tokenizers, so estimated_tokens ≈
# ceil(bytes / 4).
#
# Check points:
#   1) [blocking] estimated token count must stay below TOKEN_BUDGET.
#      The budget is a deliberate ceiling (not the current value) to leave
#      room for normal widget/property growth while catching unbounded
#      surface expansion; bump it only via an explicit, reviewed change.
#   2) [report only] current size / widget / enum counts are printed.
#
# Exit code: 1 when the budget is exceeded; otherwise 0.
#
# Usage:
#   python3 tools/check/check_api_budget.py [--root <aurora_root>]
# ============================================================================
import argparse
import json
import math
import os
import sys

# Token budget for the serialized public API (aurora_api.json).
# Baseline at introduction: ~201 KB ≈ 50.3k tokens; ceiling set ~50% higher
# to absorb normal growth while guarding against uncontrolled expansion.
TOKEN_BUDGET = 75000
CHARS_PER_TOKEN = 4


def repo_root_of(path):
    d = os.path.dirname(os.path.abspath(path))
    while d and d != os.path.dirname(d):
        if os.path.isfile(os.path.join(d, "CMakeLists.txt")):
            return d
        d = os.path.dirname(d)
    return d


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=None, help="Aurora repo root (default: two levels above this script)")
    args = ap.parse_args()
    root = args.root or repo_root_of(__file__)

    api_path = os.path.join(root, "aurora_api.json")
    if not os.path.isfile(api_path):
        print(f"[ERR] aurora_api.json not found: {api_path}", file=sys.stderr)
        return 2

    with open(api_path, encoding="utf-8") as f:
        text = f.read()
    api = json.loads(text)

    byte_count = len(text.encode("utf-8"))
    estimated_tokens = math.ceil(byte_count / CHARS_PER_TOKEN)
    widget_count = len(api.get("widgets") or [])
    enum_count = len(api.get("enums") or [])

    print(f"[INFO] aurora_api.json: {byte_count} bytes, ~{estimated_tokens} tokens "
          f"({widget_count} widgets, {enum_count} enums); budget {TOKEN_BUDGET} tokens")

    if estimated_tokens > TOKEN_BUDGET:
        print(f"[FAIL] public-API token budget exceeded: ~{estimated_tokens} > {TOKEN_BUDGET} tokens")
        print("       (spec: SPECIFICATIONS.md §4.3 / requirement #24 — keep the public surface")
        print("        token-efficient; raise TOKEN_BUDGET only via an explicit reviewed change)")
        return 1

    headroom = TOKEN_BUDGET - estimated_tokens
    print(f"[PASS] API token budget OK: ~{estimated_tokens}/{TOKEN_BUDGET} tokens ({headroom} headroom)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
