#!/usr/bin/env python3
# ============================================================================
# check_naming_conventions.py - public-API naming-consistency gate (#2)
# ----------------------------------------------------------------------------
# Spec: codespec/CODING_STANDARDS.md §11.2 (requirement #2 "极致命名一致性")
#   - 公共控件 / 枚举类型：PascalCase（Button、TextInput、Alignment…）
#   - 属性键：snake_case（on_click、font_size…），杜绝同义异名
#   - 事件名：snake_case 且 on_ 前缀（on_click、on_change…）
#   - 自由函数（debug 门面）：snake_case
#   - 枚举值：PascalCase（TopLeft、Center…）；colors 命名空间的 AURORA_*
#     常量（constexpr Color，见 core/color.h）按「常量前缀」惯例全大写，豁免
#
# Data source: aurora_api.json (the frozen API SSOT, regenerated by
# gen_api_tools; drift vs. real code is guarded separately by
# check_api_schema_sync, so this script only validates the JSON itself).
#
# Exit code: 1 on any naming violation; otherwise 0.
#
# Usage:
#   python3 tools/check/check_naming_conventions.py [--root <aurora_root>]
# ============================================================================
import argparse
import json
import os
import re
import sys

PASCAL_RE = re.compile(r"[A-Z][A-Za-z0-9]*")
SNAKE_RE = re.compile(r"[a-z][a-z0-9_]*")
# colors 命名空间常量惯例：constexpr Color AURORA_WHITE = ...（core/color.h）
CONST_RE = re.compile(r"AURORA_[A-Z0-9_]+")


def repo_root_of(path):
    d = os.path.dirname(os.path.abspath(path))
    while d and d != os.path.dirname(d):
        if os.path.isfile(os.path.join(d, "CMakeLists.txt")):
            return d
        d = os.path.dirname(d)
    return d


def check_name(kind, owner, name, pattern, violations, allow=None):
    if not isinstance(name, str) or not name:
        violations.append(f"{kind} in {owner!r}: missing/non-string name ({name!r})")
        return
    if pattern.fullmatch(name):
        return
    if allow and any(p.fullmatch(name) for p in allow):
        return
    violations.append(f"{kind} in {owner!r}: {name!r} does not match {pattern.pattern}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=None, help="Aurora repo root (default: two levels above this script)")
    args = ap.parse_args()
    root = args.root or repo_root_of(__file__)

    api_path = os.path.join(root, "aurora_api.json")
    if not os.path.isfile(api_path):
        print(f"[ERR] aurora_api.json not found: {api_path}", file=sys.stderr)
        return 2
    with open(api_path, encoding="utf-8") as f:
        api = json.load(f)

    violations = []

    # ---- Widget types: PascalCase ----
    prop_keys = set()
    event_names = set()
    widget_count = 0
    for w in api.get("widgets", []):
        owner = w.get("type", "<unknown widget>")
        widget_count += 1
        check_name("widget type", owner, w.get("type"), PASCAL_RE, violations)
        for k in (w.get("default_props") or {}):
            prop_keys.add(k)
        for k in w.get("props") or []:
            prop_keys.add(k)
        for k in (w.get("props_schema") or {}):
            prop_keys.add(k)
        for d in w.get("prop_descriptors") or []:
            if isinstance(d, dict) and d.get("name"):
                prop_keys.add(d["name"])
        # events 序列化为扁平字符串序列，每三项一组：(name, signature, description)，
        # 如 ["on_select", "void(int)", "点击某项时回调…"]；事件名统一为 on_ 前缀 snake_case。
        for ev in w.get("events") or []:
            candidates = ev if isinstance(ev, list) else [ev]
            for item in candidates:
                if isinstance(item, str) and item.startswith("on_"):
                    event_names.add(item)

    # ---- Property keys: snake_case ----
    for k in sorted(prop_keys):
        check_name("property key", "widget props", k, SNAKE_RE, violations)

    # ---- Event names: snake_case + on_ prefix ----
    for ev in sorted(event_names):
        check_name("event name", "widget events", ev, SNAKE_RE, violations)
        if isinstance(ev, str) and SNAKE_RE.fullmatch(ev) and not ev.startswith("on_"):
            violations.append(f"event name in widget events: {ev!r} must use on_ prefix")

    # ---- Enums: type PascalCase; values PascalCase (AURORA_* constants exempt) ----
    enum_count = 0
    for e in api.get("enums", []):
        owner = e.get("name", "<unknown enum>")
        enum_count += 1
        check_name("enum type", "enums", e.get("name"), PASCAL_RE, violations)
        for v in e.get("values") or []:
            check_name("enum value", owner, v, PASCAL_RE, violations, allow=[CONST_RE])

    # ---- Debug facade free functions: snake_case ----
    for fn in api.get("debug") or []:
        check_name("debug function", "aurora::debug", fn.get("name"), SNAKE_RE, violations)

    if violations:
        print(f"[FAIL] {len(violations)} public-API naming violation(s) in aurora_api.json")
        print("       (spec: CODING_STANDARDS.md §11.2 — types PascalCase, props/events/functions snake_case,")
        print("        events on_-prefixed; AURORA_* color constants are the exempt constant convention):")
        for v in violations:
            print(f"  {v}")
        return 1

    print(f"[PASS] naming conventions OK: {widget_count} widget types, {len(prop_keys)} property keys, "
          f"{len(event_names)} event names, {enum_count} enums, {len(api.get('debug') or [])} debug functions")
    return 0


if __name__ == "__main__":
    sys.exit(main())
